services:
  # MariaDB Database Service
  db:
    image: mariadb:10.6
    container_name: mariadb_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD} # Often set for development convenience
    volumes:
      - mariadb_data:/var/lib/mysql
    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "localhost",
          "-u",
          "root",
          "-p${DB_PASSWORD}",
        ]
      interval: 10s
      timeout: 5s
      retries: 5

  # Django Web Application Service
  web:
    build: .
    container_name: django_web
    restart: unless-stopped
    command: python manage.py runserver 0.0.0.0:8000
    entrypoint: ["/app/entrypoint.sh"]
    volumes:
      - .:/app
    ports:
      - "8001:8000"
    env_file:
      - ./.env
    depends_on:
      db:
        condition: service_healthy

# Define the named volume for data persistence
volumes:
  mariadb_data:
